In [23]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')

In [24]:
X, y = make_regression(n_samples= 1000, n_features= 2, noise= 7, random_state= 25)
X.shape, y.shape

((1000, 2), (1000,))

In [25]:
X

array([[ 1.03483837,  0.04077463],
       [-0.61426398, -0.53060624],
       [-1.23891855,  3.30572399],
       ...,
       [-0.17380976, -0.17601063],
       [-0.0931583 , -1.78454878],
       [-0.45411827,  0.31930162]])

In [26]:
y

array([ 8.44866043e+01, -9.98017516e+01,  2.02629584e+02,  1.09776068e+02,
        1.02977594e+02,  4.20605841e+01,  1.09019432e+02, -1.88437613e+01,
       -1.64051683e+02, -8.02134280e+01, -2.82532104e+02,  3.23167943e+01,
        2.49666091e+01, -1.14860890e+02,  6.49956207e+01,  1.21246149e+02,
        2.66119795e+02,  1.85278419e+00,  3.09278224e+01,  2.12237832e+02,
       -2.04678251e+02,  4.80226784e+01, -8.75837932e+01,  2.12613824e+01,
       -5.46886184e+01,  1.00001046e+01,  5.48457767e+01,  9.26332012e+01,
        3.59871714e+02,  1.55272445e+02,  2.51566691e+02,  5.26226252e+01,
        1.51754635e+02, -3.53840177e+01,  1.78469353e+02, -4.92468153e+01,
        4.27398580e+01,  6.94735704e+01, -6.66779216e+01, -5.96025838e+01,
        6.77041138e+01, -1.75709240e+02,  1.07961152e+02,  3.60471616e+01,
       -6.52628850e+01,  7.90001497e+01, -5.73872964e+01,  7.53362794e+01,
        1.29541602e+02, -2.63138457e+00,  1.49593963e+01,  1.70521766e+02,
        9.48905960e+01,  

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 25)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 2), (300, 2), (700,), (300,))

In [28]:
reg = KNeighborsRegressor()
reg

KNeighborsRegressor()

In [29]:
reg.fit(X_train, y_train)

KNeighborsRegressor()

In [30]:
y_pred = reg.predict(X_test)
y_pred

array([  96.15049622,    9.29275319, -219.37637794,   35.25040665,
        261.25891246,  -28.88168826,  185.97220954,  -88.46218009,
         48.56886473, -134.81272325,   78.70771435,  -69.65451573,
        159.80829727,   28.61356517,  213.02979088,   16.43365256,
        -10.55186283,   29.82821723,   42.35106462,  106.92264476,
       -251.65787321,  -70.22326291,   -9.22250405,  -26.05646888,
        110.70883275, -138.36404233, -157.95390315,  160.89662061,
         50.97136468,   74.95830008,  168.69107848, -150.95011595,
       -254.12546256,  -96.63548756,   85.95274758,  -23.3631756 ,
         61.44341973,  191.71213789,  119.8134527 ,  -21.16991176,
       -145.77782978,  -84.38297622,   -1.91222057,   27.32593041,
       -119.269406  ,  -74.42603491,  -84.61080773,   37.79651555,
        -26.12914659,  -67.93309158, -126.29040909,   99.09080255,
       -158.76389064,  179.98699362,  -28.83539236,  -38.96315781,
        225.88165324,   49.59612094, -180.82097706, -119.20931

In [31]:
#Evaluate

print(f"R2 Score: {r2_score(y_test, y_pred)}")

R2 Score: 0.9895607143070032


In [32]:
# hyperparameter tuning
params = {
    'n_neighbors': [3,5,2,8,5,9,11],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'kd_tree', 'ball_tree', 'brute'],
    'leaf_size': [20, 30, 40, 50]
}

params

{'n_neighbors': [3, 5, 2, 8, 5, 9, 11],
 'weights': ['uniform', 'distance'],
 'algorithm': ['auto', 'kd_tree', 'ball_tree', 'brute'],
 'leaf_size': [20, 30, 40, 50]}

In [33]:
grid = GridSearchCV(estimator= KNeighborsRegressor(), param_grid= params, verbose= 3, cv = 5)
grid

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'kd_tree', 'ball_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 2, 8, 5, 9, 11],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [34]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 224 candidates, totalling 1120 fits
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.980 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.981 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.987 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.983 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.986 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.981 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.984 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.990 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, 

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'kd_tree', 'ball_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 2, 8, 5, 9, 11],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [35]:
grid.best_score_

np.float64(0.9851667315003251)

In [36]:
grid.best_params_

{'algorithm': 'auto', 'leaf_size': 20, 'n_neighbors': 3, 'weights': 'distance'}

In [37]:
best_model = grid.best_estimator_
best_model

KNeighborsRegressor(leaf_size=20, n_neighbors=3, weights='distance')

In [38]:
y_tuned_pred = best_model.predict(X_test)

In [39]:
# Evaluate tuned model

print(f"R2 Score: {r2_score(y_test, y_tuned_pred)}")

R2 Score: 0.9915957158348125
