In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA   # NEW**

import warnings
warnings.filterwarnings('ignore')

In [4]:
from sklearn.datasets import load_iris
data = load_iris()

In [5]:
X = data.data
y = data.target

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 43)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [20]:
pca = PCA()
pca

PCA()

In [21]:
# by default the principal component will be equals to no of feature

X_train = pca.fit_transform(X_train)
X_train

array([[ 3.30871274e-01, -7.12842177e-01, -1.15864508e-01,
         2.47542871e-01],
       [ 2.12219645e-01, -1.24606390e+00, -8.69720214e-02,
         2.79628476e-01],
       [-1.07383395e-01, -1.17836632e+00,  3.37579418e-01,
        -4.58365837e-02],
       [ 8.37891745e-01,  3.95859121e-01,  5.29900361e-01,
        -8.29183241e-02],
       [ 7.12209934e-01,  6.68099364e-01, -1.34055679e-01,
         7.97978670e-02],
       [ 1.17364443e+00, -1.07900383e+00,  3.98660405e-01,
         3.41871445e-02],
       [ 1.79820432e-01, -8.98192474e-01,  1.69660580e-01,
        -9.43163134e-03],
       [ 1.01198788e+00,  4.05535046e-01,  4.21234525e-01,
        -1.76147775e-02],
       [ 1.09909767e+00, -8.39019181e-01, -5.05264841e-01,
         3.81251087e-02],
       [-1.96233671e+00,  3.57260302e-01,  4.10106171e-01,
         1.28342977e-04],
       [ 2.90460244e-01, -1.69847623e+00, -9.73898723e-01,
         1.18065487e-01],
       [ 2.77268400e+00,  7.05171458e-01,  5.99336017e-01,
      

In [23]:
X_test = scaler.transform(X_test)
X_test = pca.transform(X_test)
X_test

array([[ -8.8370991 ,  -7.21889195,  -2.89709873,  -3.37269342],
       [ -8.38798754,  -5.01824922,  -2.96248332,  -3.37269342],
       [ -7.04065288,  -7.76905263,  -1.85094521,  -0.64423955],
       [ -7.34006059,  -9.41953468,  -2.07979129,  -2.00846649],
       [ -4.64539127,  -7.76905263,  -1.26248385,  -0.13265445],
       [ -8.38798754,  -5.56840991,  -2.92979102,  -3.37269342],
       [ -7.48976444, -10.51985604,  -1.78556061,  -0.30318281],
       [ -6.89094903,  -8.869374  ,  -2.11248359,  -1.49688138],
       [ -7.78917214, -11.07001672,  -2.21056048,  -2.00846649],
       [ -8.68739525, -11.07001672,  -2.34132967,  -2.00846649],
       [ -9.4359145 ,  -7.76905263,  -2.99517562,  -3.37269342],
       [ -5.84302207,  -8.869374  ,  -1.85094521,  -1.32635302],
       [ -4.49568741,  -8.869374  ,  -1.22979156,  -0.30318281],
       [ -8.8370991 ,  -5.56840991,  -2.89709873,  -3.37269342],
       [ -7.04065288,  -8.31921331,  -1.9490221 ,  -1.15582465],
       [ -6.74124518,  -8

In [24]:
pca.components_

array([[ 1.00000000e+00, -1.87589701e-18,  9.40709830e-17,
         2.62198052e-17],
       [ 1.87589701e-18,  1.00000000e+00,  3.33066907e-16,
         0.00000000e+00],
       [-9.40709830e-17, -2.22044605e-16,  1.00000000e+00,
        -4.16333634e-15],
       [-2.62198052e-17,  5.55111512e-17,  4.16333634e-15,
         1.00000000e+00]])

In [25]:
X_train.shape

(105, 4)

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
X_train = scaler.fit_transform(X_train)

pca = PCA(n_components=3)  #We want 3 components
X_train = pca.fit_transform(X_train)
X_train

array([[-2.13962242,  0.51361087,  0.19941949],
       [-1.99540185,  0.88230113,  0.52959118],
       [ 2.56560809,  2.52456203,  0.33632421],
       [ 1.8817921 ,  0.61359371,  0.09892703],
       [ 2.32153724,  0.26701273,  0.72243786],
       [ 1.84467374, -0.24451667, -0.31650583],
       [ 1.15280787, -0.35008471, -0.10932997],
       [ 0.4790508 ,  0.95287966, -0.36125388],
       [ 2.91219047,  0.19158127,  0.93078197],
       [ 0.08675571, -0.11160955, -0.10833625],
       [-2.30153266,  0.41060989, -0.07682428],
       [ 1.1891939 , -1.19987449, -0.60657463],
       [ 1.30073832, -0.54682835,  0.01597452],
       [-2.24450247, -0.52508153,  0.19211146],
       [-2.36828766, -0.08838333, -0.05808824],
       [ 1.87797779,  0.25405905, -0.32784673],
       [-2.42517095,  0.34914986, -0.32307822],
       [ 1.02242019,  0.07912786, -0.29250815],
       [ 1.39809419,  0.69776328, -0.19862401],
       [ 0.90251119,  0.48222885,  0.56632856],
       [ 0.35933115, -0.56530436, -0.126

In [29]:
pca.n_components

3

In [30]:
pca.components_

array([[ 0.539189  , -0.20375871,  0.58658648,  0.56892346],
       [ 0.28543082,  0.95620505,  0.00732108,  0.06440146],
       [ 0.74201139, -0.17785208, -0.12967908, -0.63322277]])

In [31]:
pca.explained_variance_ratio_

array([0.71618786, 0.23946458, 0.03982701])

In [32]:
pca.explained_variance_

array([2.89368831, 0.96753367, 0.16091722])

In [ ]:
#for visualisation

# Code source: Gaël Varoquaux
# License: BSD 3 clause

import matplotlib.pyplot as plt

# unused but required import for doing 3d projections with matplotlib < 3.2
import mpl_toolkits.mplot3d  # noqa: F401
import numpy as np

from sklearn import datasets, decomposition

np.random.seed(5)

iris = datasets.load_iris()
X = iris.data
y = iris.target

fig = plt.figure(1, figsize=(4, 3))
plt.clf()

ax = fig.add_subplot(111, projection="3d", elev=48, azim=134)
ax.set_position([0, 0, 0.95, 1])


plt.cla()
pca = decomposition.PCA(n_components=3)
pca.fit(X)
X = pca.transform(X)

for name, label in [("Setosa", 0), ("Versicolour", 1), ("Virginica", 2)]:
    ax.text3D(
        X[y == label, 0].mean(),
        X[y == label, 1].mean() + 1.5,
        X[y == label, 2].mean(),
        name,
        horizontalalignment="center",
        bbox=dict(alpha=0.5, edgecolor="w", facecolor="w"),
    )
# Reorder the labels to have colors matching the cluster results
y = np.choose(y, [1, 2, 0]).astype(float)
ax.scatter(X[:, 0], X[:, 1], X[:, 2], c=y, cmap=plt.cm.nipy_spectral, edgecolor="k")

ax.xaxis.set_ticklabels([])
ax.yaxis.set_ticklabels([])
ax.zaxis.set_ticklabels([])

plt.show()