#Adaboost classifier

In [55]:
#adaboost classfier

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split


from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


import warnings
warnings.filterwarnings('ignore')

In [56]:
from scipy.sparse import random_array
X,y = make_classification(n_samples= 1000, n_features= 20, n_classes= 2, random_state= 1)
X.shape, y.shape

((1000, 20), (1000,))

In [57]:
X

array([[-2.04582165, -0.13791624, -0.08071423, ...,  2.48194524,
         0.74236675,  0.23154789],
       [-0.98726024,  1.30120189,  2.37734888, ...,  0.55445754,
        -0.21892143, -0.37608578],
       [ 0.57335921,  0.09375582,  0.4662521 , ..., -0.6088508 ,
         0.79903499, -0.17121177],
       ...,
       [-0.70737159,  1.07650943,  0.58510456, ..., -1.51337602,
         0.90239871, -0.69230951],
       [-0.20706849,  1.17319848, -1.94478665, ..., -0.32820676,
         1.5711921 ,  1.14877729],
       [-2.16769231, -2.54871672,  2.89359255, ...,  0.71535366,
         0.34329241,  1.07350284]])

In [58]:
y

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [60]:
classifier = AdaBoostClassifier()
classifier

AdaBoostClassifier()

In [61]:
classifier.fit(X_train, y_train)

AdaBoostClassifier()

In [62]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1])

In [63]:
#Evaluate the model

print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print()
print("Classification Report:")
print(classification_report(y_test, y_pred))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy Score: 0.8533333333333334

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       139
           1       0.87      0.85      0.86       161

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300


Confusion Matrix:
[[119  20]
 [ 24 137]]


In [64]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1.0, 1.5, 2.0],
    'algorithm': ['SAMME']
}

In [65]:
ada = AdaBoostClassifier()

clf = GridSearchCV(estimator= ada, param_grid= param_grid, cv= 5, verbose= 3)
clf

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'algorithm': ['SAMME'],
                         'learning_rate': [0.01, 0.1, 1.0, 1.5, 2.0],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [66]:
clf.fit(X_train, y_train)

Fitting 5 folds for each of 15 candidates, totalling 75 fits
[CV 1/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.857 total time=   0.2s
[CV 2/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.857 total time=   0.1s
[CV 3/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.857 total time=   0.1s
[CV 4/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.807 total time=   0.1s
[CV 5/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=50;, score=0.821 total time=   0.1s
[CV 1/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.857 total time=   0.3s
[CV 2/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.857 total time=   0.3s
[CV 3/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.857 total time=   0.3s
[CV 4/5] END algorithm=SAMME, learning_rate=0.01, n_estimators=100;, score=0.807 total time=   0.3s
[CV 5/5] END algorithm=SAMME, learning_rate=

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'algorithm': ['SAMME'],
                         'learning_rate': [0.01, 0.1, 1.0, 1.5, 2.0],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [67]:
clf.best_score_

np.float64(0.8585714285714285)

In [68]:
clf.best_params_

{'algorithm': 'SAMME', 'learning_rate': 0.1, 'n_estimators': 200}

In [69]:
best_model = clf.best_estimator_
best_model

AdaBoostClassifier(algorithm='SAMME', learning_rate=0.1, n_estimators=200)

In [70]:
y_pred = best_model.predict(X_test)

print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print()
print("Classification Report:")
print(classification_report(y_test, y_pred))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy Score: 0.8566666666666667

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.86      0.85       139
           1       0.88      0.85      0.86       161

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300


Confusion Matrix:
[[120  19]
 [ 24 137]]


# Adaboost regressor

In [71]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [82]:
X,y = make_regression(n_samples= 1500, n_features= 25, noise= 10)

In [83]:
X.shape, y.shape

((1500, 25), (1500,))

In [84]:
X

array([[ 0.28142298,  1.35567417, -0.63904884, ..., -0.47012932,
        -0.69783599, -0.32785939],
       [-0.01732985, -1.90149363, -1.04140645, ...,  2.22946827,
         1.31266637,  0.55833539],
       [ 0.82644457,  0.31680818, -0.0537012 , ...,  1.50552844,
        -1.26904225, -0.0054913 ],
       ...,
       [ 0.41551527,  0.65953557, -0.97839248, ...,  1.05090813,
        -0.86929687, -2.56910821],
       [ 0.61403216, -0.77371546, -0.30046739, ...,  1.1564264 ,
        -0.14702447,  0.22472829],
       [ 1.36784262,  0.12248236,  0.26915494, ...,  0.70694657,
        -0.94177015, -2.02018721]])

In [85]:
y

array([-185.01704607, -138.23790304,    4.63569449, ...,  215.44162104,
        238.2939423 ,  -92.02408905])

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [87]:
regressor = AdaBoostRegressor()
regressor

AdaBoostRegressor()

In [88]:
regressor.fit(X_train, y_train)

AdaBoostRegressor()

In [89]:
y_pred = regressor.predict(X_test)
y_pred

array([-181.35408715, -239.94477999,  134.10563309,  108.97749077,
        -56.22807927,   29.64536146,   59.91226045,   46.14218816,
         33.09566348,  161.25504162,  288.89774566, -121.24208522,
       -121.24208522, -174.25652904, -227.55451769,  164.52925898,
        154.87740475,  161.25504162,  159.39381498, -123.07266772,
         86.31886355, -131.51102669,  126.75067618,  249.04003296,
         67.26444519,   29.64536146,  144.70207478,   67.26444519,
        -35.94919633,   37.67982315,   23.03178457,  148.77779497,
        104.40037348,  -54.63271619,  151.20805462,   37.67982315,
       -227.55451769,   61.57997774,  218.42802064,  101.28015953,
        -55.61323856, -227.27831875,   60.85327314,  229.76883106,
        161.25504162,   68.28423088, -189.93813812, -213.70009522,
       -213.70009522,   29.64536146,   23.73343978,   59.91226045,
       -171.83871177,   33.09566348, -181.35408715,   40.80408356,
         41.32705817,  -56.22807927,  256.27050817,  -64.28169

In [90]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [91]:
#Evaluate the model

print("Model Performance")
print()
print(f"R2 Score: {r2_score(y_test, y_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")

Model Performance

R2 Score: 0.7250541454285355
Mean Absolute Error: 81.55934269019208
Mean Squared Error: 11073.116360954853


In [92]:
param_grid= {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 0.5, 1.0, 1.5],
    'loss':  ['linear', 'square', 'exponential']
}

reg = GridSearchCV(estimator= regressor, param_grid= param_grid, cv= 5, verbose= 3)
reg

GridSearchCV(cv=5, estimator=AdaBoostRegressor(),
             param_grid={'learning_rate': [0.01, 0.1, 0.5, 1.0, 1.5],
                         'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [93]:
reg.fit(X_train, y_train)

Fitting 5 folds for each of 45 candidates, totalling 225 fits
[CV 1/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.433 total time=   0.5s
[CV 2/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.475 total time=   0.5s
[CV 3/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.479 total time=   0.5s
[CV 4/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.425 total time=   0.5s
[CV 5/5] END learning_rate=0.01, loss=linear, n_estimators=50;, score=0.467 total time=   0.4s
[CV 1/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.444 total time=   1.0s
[CV 2/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.499 total time=   1.3s
[CV 3/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.491 total time=   1.0s
[CV 4/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.423 total time=   0.9s
[CV 5/5] END learning_rate=0.01, loss=linear, n_estimators=100;, score=0.475 to

GridSearchCV(cv=5, estimator=AdaBoostRegressor(),
             param_grid={'learning_rate': [0.01, 0.1, 0.5, 1.0, 1.5],
                         'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [50, 100, 200]},
             verbose=3)

In [94]:
reg.best_params_

{'learning_rate': 1.5, 'loss': 'square', 'n_estimators': 200}

In [95]:
reg.best_score_

np.float64(0.819520009348721)

In [96]:
best_model = reg.best_estimator_
best_model

AdaBoostRegressor(learning_rate=1.5, loss='square', n_estimators=200)

In [97]:
y_pred_tuned = best_model.predict(X_test)

In [98]:
print("Regressor Model Performance")
print()
print(f"R2 Score: {r2_score(y_test, y_pred_tuned)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred_tuned)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred_tuned)}")

Regressor Model Performance

R2 Score: 0.8423106455775566
Mean Absolute Error: 60.0043938995555
Mean Squared Error: 6350.750670982436
