In [28]:
# Gradient Boosting Classifier

In [29]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import warnings
warnings.filterwarnings('ignore')

In [30]:
X, y = make_classification(n_samples= 1200, n_features= 10, n_classes= 2)
X.shape, y.shape

((1200, 10), (1200,))

In [31]:
X

array([[ 0.72243438, -0.64338609, -1.74492879, ..., -0.70940892,
        -2.85975439, -2.14026488],
       [-1.15397838,  0.00742251, -0.41212171, ..., -0.45564904,
        -0.53513278,  0.39567941],
       [ 1.06001097, -0.94502248,  0.32235937, ...,  1.88431015,
         0.18894921,  0.57678106],
       ...,
       [-1.17781943,  0.74134188, -0.18771316, ..., -0.89115187,
         1.47879922, -0.03267826],
       [-0.58393889, -1.79406533,  1.37770038, ..., -0.81647821,
         0.91548057, -0.62849077],
       [-0.84761236,  2.25854179,  0.31869306, ..., -1.18875566,
         0.75654089, -0.34943643]])

In [32]:
y

array([1, 0, 1, ..., 0, 0, 1])

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((960, 10), (240, 10), (960,), (240,))

In [34]:
clf = GradientBoostingClassifier()
clf

GradientBoostingClassifier()

In [35]:
clf.fit(X_train, y_train)

GradientBoostingClassifier()

In [36]:
y_pred = clf.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [37]:
# Evaluation
print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print(f"{classification_report(y_test, y_pred)}")
print(f"{confusion_matrix(y_test, y_pred)}")

Accuracy Score: 0.8875
              precision    recall  f1-score   support

           0       0.87      0.94      0.90       131
           1       0.92      0.83      0.87       109

    accuracy                           0.89       240
   macro avg       0.89      0.88      0.89       240
weighted avg       0.89      0.89      0.89       240

[[123   8]
 [ 19  90]]


In [38]:
# Hyperparameter tuning
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.05, 0.2],
#     'max_depth': [3, 4, 5],
#     'subsample': [0.8, 0.9, 1.0],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4]
}

In [39]:
gb_clf = GradientBoostingClassifier()
grid_search = GridSearchCV(estimator= gb_clf, param_grid= param_grid, cv= 5, verbose= 3)
grid_search

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 0.05, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [40]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END learning_rate=0.01, n_estimators=100;, score=0.906 total time=   0.5s
[CV 2/5] END learning_rate=0.01, n_estimators=100;, score=0.906 total time=   0.5s
[CV 3/5] END learning_rate=0.01, n_estimators=100;, score=0.922 total time=   0.5s
[CV 4/5] END learning_rate=0.01, n_estimators=100;, score=0.911 total time=   0.5s
[CV 5/5] END learning_rate=0.01, n_estimators=100;, score=0.917 total time=   0.5s
[CV 1/5] END learning_rate=0.01, n_estimators=200;, score=0.927 total time=   1.0s
[CV 2/5] END learning_rate=0.01, n_estimators=200;, score=0.917 total time=   1.0s
[CV 3/5] END learning_rate=0.01, n_estimators=200;, score=0.932 total time=   1.0s
[CV 4/5] END learning_rate=0.01, n_estimators=200;, score=0.917 total time=   1.4s
[CV 5/5] END learning_rate=0.01, n_estimators=200;, score=0.927 total time=   1.3s
[CV 1/5] END learning_rate=0.01, n_estimators=300;, score=0.927 total time=   1.5s
[CV 2/5] END learning_rate

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.01, 0.1, 0.05, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [41]:
grid_search.best_params_

{'learning_rate': 0.1, 'n_estimators': 200}

In [42]:
grid_search.best_score_

np.float64(0.9270833333333334)

In [43]:
grid_search.best_estimator_

GradientBoostingClassifier(n_estimators=200)

In [44]:
best_model = grid_search.best_estimator_
best_model

GradientBoostingClassifier(n_estimators=200)

In [45]:
y_tuned_pred = best_model.predict(X_test)

# Evaluate the tuned model
print(f"Accuracy Score: {accuracy_score(y_test, y_tuned_pred)}")
print(f"{classification_report(y_test, y_tuned_pred)}")
print(f"{confusion_matrix(y_test, y_tuned_pred)}")

Accuracy Score: 0.8875
              precision    recall  f1-score   support

           0       0.87      0.93      0.90       131
           1       0.91      0.83      0.87       109

    accuracy                           0.89       240
   macro avg       0.89      0.88      0.89       240
weighted avg       0.89      0.89      0.89       240

[[122   9]
 [ 18  91]]
