In [19]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import warnings
warnings.filterwarnings('ignore')

In [20]:
X, y = make_regression(n_samples= 1200, n_features= 3, noise= 10)
X.shape, y.shape

((1200, 3), (1200,))

In [21]:
X

array([[-0.64546292,  0.56576858, -0.68043287],
       [ 0.31680279, -0.83761086, -0.5956011 ],
       [ 0.47813604,  1.85408295,  1.40091336],
       ...,
       [-1.46176627,  0.00970716, -0.41118996],
       [ 1.55088197, -0.83594644, -1.28126303],
       [-1.53565079,  0.30198172,  0.34681881]])

In [22]:
y

array([-11.3156432 , -89.47644067, 245.08247301, ..., -82.85709696,
       -57.86336482, -43.74555485])

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((840, 3), (360, 3), (840,), (360,))

In [24]:
regressor = GradientBoostingRegressor()
regressor

GradientBoostingRegressor()

In [25]:
regressor.fit(X_train, y_train)

GradientBoostingRegressor()

In [26]:
y_pred = regressor.predict(X_test)
y_pred

array([-143.36381844, -278.02564048,   82.38556098,  142.64760039,
         95.33573659,  160.78453169,  -63.2910925 ,   25.24091639,
        -70.7895344 , -140.13381776,   90.56524119,    6.08993461,
         57.50954279,  179.12254678, -143.21379229,  -65.9029339 ,
       -149.72377815, -134.16512306,  -12.40182293,  150.76122179,
        -78.40422629,   20.29604199,  -19.69229305,  127.72777614,
        -12.65811162,  140.5561716 ,  -77.91739468,    7.42810736,
         77.17334923,  -59.49462511,  -58.88265644,  164.82530121,
       -156.64358521,   15.89219267,  112.62591318, -122.04259154,
         11.82391639,   60.84772224,    9.85632993,  -12.00184061,
       -164.27570052,  -97.22503443,  111.35985047,   77.51955705,
        -18.54307586,   13.79213778,   96.01557207,  -80.23056273,
        114.56108578,  -97.37471272,  -82.4797081 ,  -16.5470887 ,
        110.53996877,  -15.00577306,  -53.69817404,   -1.46466418,
        -92.99431725,  275.61238066,  -14.33732138,   19.80309

In [27]:
# Evaluate the model

print(f"R2 Score: {r2_score(y_test, y_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")

R2 Score: 0.981937798056152
Mean Absolute Error: 11.514226201403575
Mean Squared Error: 209.25354005426246


In [28]:
# hyperparameter tuning
from sklearn.model_selection import GridSearchCV

# Param grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.05, 0.2],
#     'max_depth': [3, 4, 5],
#     'subsample': [0.8, 0.9, 1.0],
#     'min_samples_split': [2, 5, 10],
#     'min_samples_leaf': [1, 2, 4]
}

In [29]:
gb_regressor = GradientBoostingRegressor()

grid_search = GridSearchCV(estimator= gb_regressor, param_grid= param_grid, cv= 5, verbose= 3)
grid_search

GridSearchCV(cv=5, estimator=GradientBoostingRegressor(),
             param_grid={'learning_rate': [0.01, 0.1, 0.05, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [30]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END learning_rate=0.01, n_estimators=100;, score=0.728 total time=   0.2s
[CV 2/5] END learning_rate=0.01, n_estimators=100;, score=0.709 total time=   0.2s
[CV 3/5] END learning_rate=0.01, n_estimators=100;, score=0.719 total time=   0.2s
[CV 4/5] END learning_rate=0.01, n_estimators=100;, score=0.759 total time=   0.2s
[CV 5/5] END learning_rate=0.01, n_estimators=100;, score=0.738 total time=   0.2s
[CV 1/5] END learning_rate=0.01, n_estimators=200;, score=0.890 total time=   0.5s
[CV 2/5] END learning_rate=0.01, n_estimators=200;, score=0.875 total time=   0.5s
[CV 3/5] END learning_rate=0.01, n_estimators=200;, score=0.888 total time=   0.5s
[CV 4/5] END learning_rate=0.01, n_estimators=200;, score=0.909 total time=   0.5s
[CV 5/5] END learning_rate=0.01, n_estimators=200;, score=0.893 total time=   0.5s
[CV 1/5] END learning_rate=0.01, n_estimators=300;, score=0.941 total time=   0.5s
[CV 2/5] END learning_rate

GridSearchCV(cv=5, estimator=GradientBoostingRegressor(),
             param_grid={'learning_rate': [0.01, 0.1, 0.05, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [31]:
grid_search.best_params_

{'learning_rate': 0.1, 'n_estimators': 300}

In [32]:
grid_search.best_score_

np.float64(0.9830597101092738)

In [33]:
best_model = grid_search.best_estimator_
best_model

GradientBoostingRegressor(n_estimators=300)

In [34]:
y_tuned_pred = best_model.predict(X_test)

# Evaluate Tuned model
print(f"R2 Score: {r2_score(y_test, y_tuned_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_tuned_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_tuned_pred)}")

R2 Score: 0.9849359929503635
Mean Absolute Error: 10.681440560216684
Mean Squared Error: 174.5189657572425
