## XG Boost Regressor

In [92]:
# !pip install xgboost

In [93]:
# XGBoost Regressor

from xgboost import XGBRegressor

In [94]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [95]:
X, y = make_regression(n_samples= 1000, n_features= 2, noise= 10, random_state=12)

In [96]:
X

array([[-0.20615695, -0.4823685 ],
       [-0.98394708,  1.34791841],
       [ 0.29363622,  0.11560625],
       ...,
       [-0.88264452,  0.44698124],
       [-1.2056456 , -0.38154484],
       [ 0.27845861, -1.37620297]])

In [97]:
y

array([-6.32008299e+01,  2.22449631e+01,  2.70482704e+01,  5.38864794e+01,
        1.54474718e+02,  1.43184753e+02, -4.63726536e+01, -5.19170643e+01,
        1.08038432e+01, -2.32485750e+02,  1.11755204e+02,  4.77014206e+01,
        1.45182233e+02, -1.58268476e+02, -6.34145454e+01, -7.69391680e+01,
        8.74305235e+01, -1.16348359e+02,  1.18388814e+02,  1.49072857e+02,
        2.84829821e+02, -2.74082771e+00, -1.51850520e+02, -1.45040936e+02,
       -6.00607357e+01, -7.87386049e+01,  1.06949181e+01,  3.94724286e+01,
        2.59235464e+01,  1.25703865e+02, -3.54935342e+01,  5.44939223e+01,
       -8.04867998e+01,  3.74981520e+01,  2.73019804e+01, -2.02318324e+01,
       -4.90415611e+01, -3.72052211e+01, -7.30460408e+01, -7.26956919e+01,
        1.73125904e+01, -2.05843763e+01,  5.76393291e+01, -3.23550618e+02,
       -1.39933277e+02,  9.19171922e-01,  1.22613760e+01, -3.57251207e+01,
        9.65976129e+01, -6.62318954e-01, -6.90137895e+01,  5.32736168e+01,
       -6.22519989e+00, -

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 2)

In [99]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 2), (300, 2), (700,), (300,))

In [100]:
regressor = XGBRegressor()
regressor

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [101]:
regressor.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [102]:
y_pred = regressor.predict(X_test)

#Evaluate the model
print(f"R2 Score: {r2_score(y_test, y_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")

R2 Score: 0.9822424954519724
Mean Absolute Error: 11.614013759337228
Mean Squared Error: 197.7442615053843


In [103]:
from sklearn.model_selection import GridSearchCV


param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.5, 0.05, 0.1, 0.2]
}

In [104]:
gs_reg = XGBRegressor()
grid_search = GridSearchCV(estimator= gs_reg, param_grid= param_grid, cv= 5, verbose= 3, n_jobs= -1)
grid_search

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, max_bin=None,
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.5, 0.05, 0.1, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [105]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 15 candidates, totalling 75 fits


GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, feature_weights=None,
                                    gamma=None, grow_policy=None,
                                    importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, max_bin=None,
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.5, 0.05, 0.1, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [106]:
grid_search.best_params_

{'learning_rate': 0.05, 'n_estimators': 200}

In [107]:
grid_search.best_score_

np.float64(0.9796966731849652)

In [108]:
best_model = grid_search.best_estimator_

y_tuned_pred = best_model.predict(X_test)

#Evaluate the model
print(f"R2 Score: {r2_score(y_test, y_tuned_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_tuned_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_tuned_pred)}")

R2 Score: 0.9847513155184171
Mean Absolute Error: 10.466330018247023
Mean Squared Error: 169.80650876838237


## XG Boost Classifier

In [109]:
from xgboost import XGBClassifier

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [110]:
# Generate dataset
X, y = make_classification(n_samples= 1000, n_features= 20, n_classes= 2, random_state=42)

In [111]:
X.shape, y.shape

((1000, 20), (1000,))

In [112]:
X

array([[-0.6693561 , -1.49577819, -0.87076638, ..., -1.26733697,
        -1.2763343 ,  1.01664321],
       [ 0.09337237,  0.78584826,  0.10575379, ..., -0.12270893,
         0.6934308 ,  0.91136272],
       [-0.90579721, -0.60834121,  0.29514098, ...,  0.83049813,
        -0.73733198, -0.5782121 ],
       ...,
       [-0.20013455, -1.46108168,  1.79701652, ..., -1.50280171,
        -1.27473745,  1.60111869],
       [ 0.03935575,  0.24868361, -0.47532342, ...,  0.09912579,
         0.54269228,  1.20827474],
       [ 0.76921528,  0.47076539,  0.16994471, ...,  0.6561162 ,
         0.64333186, -2.02100232]])

In [113]:
y

array([1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 2)

In [115]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 20), (300, 20), (700,), (300,))

In [116]:
clf = XGBClassifier()
clf

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [117]:
clf.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [118]:
y_pred = clf.predict(X_test)

#Evaluate the model
print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")

Accuracy Score: 0.8933333333333333
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.93      0.89       141
           1       0.93      0.86      0.90       159

    accuracy                           0.89       300
   macro avg       0.89      0.90      0.89       300
weighted avg       0.90      0.89      0.89       300

Confusion Matrix:
[[131  10]
 [ 22 137]]


In [119]:
from sklearn.model_selection import GridSearchCV


param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.5, 0.05, 0.1, 0.2]
}

In [120]:
gs_clf = XGBClassifier()
grid_search = GridSearchCV(estimator= gs_clf, param_grid= param_grid, cv= 5, verbose= 3, n_jobs= -1)
grid_search

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_bin=None,
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.5, 0.05, 0.1, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [ ]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 15 candidates, totalling 75 fits


In [ ]:
grid_search.best_params_

In [ ]:
grid_search.best_score_

In [ ]:
best_model = grid_search.best_estimator_
best_model

In [ ]:
y_tuned_pred = best_model.predict(X_test)

#Evaluate the model
print(f"Accuracy Score: {accuracy_score(y_test, y_tuned_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_tuned_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_tuned_pred)}")