# CatBoost Classifier

In [36]:
# !pip install catboost

In [37]:
from catboost import CatBoostClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [38]:
X, y = make_classification(n_samples= 1000, n_features= 20, n_classes= 2, random_state= 33)
X.shape, y.shape

((1000, 20), (1000,))

In [8]:
X

array([[ 1.16669371,  0.08135148, -2.08401738, ..., -0.55859321,
         1.95662012,  1.9538476 ],
       [-1.27354172, -1.16267495,  0.34171742, ...,  0.34764629,
         1.28048504, -1.31369127],
       [-0.21985884,  0.85432149,  0.52297165, ..., -0.48341405,
         0.2216946 ,  0.58340674],
       ...,
       [-1.11650766,  0.71192452,  1.36070998, ...,  0.23487378,
        -1.18485101,  0.90856852],
       [-2.83816122,  1.46973836,  0.93537047, ..., -0.71699629,
         1.06848385, -0.43924778],
       [ 0.31786492,  0.16306361,  0.42289802, ..., -0.23337803,
        -0.62147723, -0.82004957]])

In [9]:
y

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0,

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.3, random_state= 33)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 20), (300, 20), (700,), (300,))

In [15]:
classifier = CatBoostClassifier()  #If you don't want details in training put verbose= 0
classifier

In [ ]:
classifier.fit(X_train, y_train)

In [19]:
y_pred = classifier.predict(X_test)

#Evaluate the model
print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print(f"Classification Report: \n{classification_report(y_test, y_pred)}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")

Accuracy Score: 0.9566666666666667
Classification Report: 
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       154
           1       0.97      0.95      0.96       146

    accuracy                           0.96       300
   macro avg       0.96      0.96      0.96       300
weighted avg       0.96      0.96      0.96       300

Confusion Matrix: 
[[149   5]
 [  8 138]]


In [33]:
# Hyperparameter tuning

params = {
    'n_estimators': [100,200,300],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'depth': [3,4,5,6]
}

In [34]:
grid_search = GridSearchCV(estimator= CatBoostClassifier(verbose=0), param_grid= params, cv= 5, n_jobs= -1, verbose= 3)
grid_search

GridSearchCV(cv=5,
             estimator=<catboost.core.CatBoostClassifier object at 0x791393199550>,
             n_jobs=-1,
             param_grid={'depth': [3, 4, 5, 6],
                         'learning_rate': [0.01, 0.05, 0.1, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [35]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits


GridSearchCV(cv=5,
             estimator=<catboost.core.CatBoostClassifier object at 0x791393199550>,
             n_jobs=-1,
             param_grid={'depth': [3, 4, 5, 6],
                         'learning_rate': [0.01, 0.05, 0.1, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=3)

In [39]:
grid_search.best_score_

np.float64(0.96)

In [40]:
grid_search.best_params_

{'depth': 6, 'learning_rate': 0.1, 'n_estimators': 100}

In [41]:
best_model = grid_search.best_estimator_
best_model

In [42]:
y_tuned_pred = best_model.predict(X_test)

#Evaluate the model
print(f"Accuracy Score: {accuracy_score(y_test, y_tuned_pred)}")
print(f"Classification Report: \n{classification_report(y_test, y_tuned_pred)}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_tuned_pred)}")

Accuracy Score: 0.96
Classification Report: 
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       154
           1       0.97      0.95      0.96       146

    accuracy                           0.96       300
   macro avg       0.96      0.96      0.96       300
weighted avg       0.96      0.96      0.96       300

Confusion Matrix: 
[[150   4]
 [  8 138]]


# CatBoost Regressor

In [43]:
from catboost import CatBoostRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [44]:
X, y = make_regression(n_samples= 1000, n_features= 2, noise= 10, random_state= 35)
X.shape, y.shape

((1000, 2), (1000,))

In [46]:
regressor = CatBoostRegressor(verbose= 0)
regressor

In [47]:
regressor.fit(X_train, y_train)

In [48]:
# Predict
y_pred = regressor.predict(X_test)

#Evaluate
print(f"R2 Score: {r2_score(y_test, y_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred)}")

R2 Score: 0.858328294495457
Mean Absolute Error: 0.0854300575278941
Mean Squared Error: 0.03539274029515717


In [49]:
# Parameter Tuning

params = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'depth': [3,4,5,6]
}

In [50]:
grid_search = GridSearchCV(estimator= CatBoostRegressor(verbose= 0), param_grid= params, cv= 5, n_jobs= -1, verbose= 2)
grid_search

GridSearchCV(cv=5,
             estimator=<catboost.core.CatBoostRegressor object at 0x791393628e60>,
             n_jobs=-1,
             param_grid={'depth': [3, 4, 5, 6],
                         'learning_rate': [0.01, 0.05, 0.1, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=2)

In [51]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits


GridSearchCV(cv=5,
             estimator=<catboost.core.CatBoostRegressor object at 0x791393628e60>,
             n_jobs=-1,
             param_grid={'depth': [3, 4, 5, 6],
                         'learning_rate': [0.01, 0.05, 0.1, 0.2],
                         'n_estimators': [100, 200, 300]},
             verbose=2)

In [ ]:
# Best Parameters
print(f"Best Parameters: {grid_search.best_params_}")

# Best Score
print(f"Best Score: {grid_search.best_score_}")

# Best model training
best_model = grid_search.best_estimator_

# Predict
y_tuned_pred = best_model.predict(X_test)

# Evaluation of tuned model
print(f"R2 Score: {r2_score(y_test, y_tuned_pred)}")
print(f"Mean Absolute Error: {mean_absolute_error(y_test, y_tuned_pred)}")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_tuned_pred)}")